version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - JWT_ACCESS_SECRET=secret
      - JWT_REFRESH_SECRET=secret
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: vkovalenko
      POSTGRES_DB: commentservice
